name: Github actions OIDC-GCP
on:
  push:
    branches: 
    - master

jobs:
  OIDC:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: 'projects/776508433270/locations/global/workloadIdentityPools/oidc-github-pool/attribute.repository/assertion.repository'
          service_account: 'github-oidc@gleaming-baton-410613.iam.gserviceaccount.com'

      - name: 'setup gcloud'
        uses: 'google-github-actions/setup-gcloud@v1'
  ##      
      - name: 'build-push'
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker build -t nginx-app .
          docker tag nginx-app europe-west3-docker.pkg.dev/gleaming-baton-410613/fin-oidc:${GITHUB_SHA}       
          docker push europe-west3-docker.pkg.dev/gleaming-baton-410613/fin-oidc:${GITHUB_SHA} 

